[package]
name = "nu-signature"
version = "0.1.0"
edition = "2021"

[workspace]
members = [
    "crates/nu-signature-core"
]

[lib]
proc-macro = true

[dependencies]
nu-signature-core = {version = "0.1.0", path = "crates/nu-signature-core" }